### PR TITLE
fix #2 via a property settable in tests.

### LINKED ISSUE #2: Test errors in Tests+Privacy.swift when running tests on the command line.
Below is the sample build log and sequence of commands I did on the command line where I see the errors.

The log below is for the build is being done using the fixes in #3 so as to test Xcode 12.5.1 (Swift 5.4.2).

Doing this build in Xcode 12.5.1 by opening the package folder and then running tests _works without test failures_.

Likewise on main pre-PR-merged-branch, these tests succeed in Xcode 13.0 but fail on the command line. 

```
Logging % sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

Logging % swift --version
swift-driver version: 1.26.9 Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
Target: arm64-apple-macosx11.0

Logging % swift package clean 

Logging % swift test
[14/14] Build complete!
Test Suite 'All tests' started at 2021-09-22 15:58:43.731
Test Suite 'LoggingPackageTests.xctest' started at 2021-09-22 15:58:43.731
Test Suite 'FloatTests' started at 2021-09-22 15:58:43.731
Test Case '-[LoggingTests.FloatTests testFloats]' started.
Test Case '-[LoggingTests.FloatTests testFloats]' passed (0.002 seconds).
Test Suite 'FloatTests' passed at 2021-09-22 15:58:43.733.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.002 (0.002) seconds
Test Suite 'IntegerTests' started at 2021-09-22 15:58:43.733
Test Case '-[LoggingTests.IntegerTests testSigned]' started.
Test Case '-[LoggingTests.IntegerTests testSigned]' passed (0.000 seconds).
Test Case '-[LoggingTests.IntegerTests testUnsigned]' started.
Test Case '-[LoggingTests.IntegerTests testUnsigned]' passed (0.000 seconds).
Test Suite 'IntegerTests' passed at 2021-09-22 15:58:43.734.
	 Executed 2 tests, with 0 failures (0 unexpected) in 0.000 (0.001) seconds
Test Suite 'PrivateTests' started at 2021-09-22 15:58:43.734
Test Case '-[LoggingTests.PrivateTests testPrivate]' started.
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:16: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("name") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:19: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("-3.141593") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:21: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("-3") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:23: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("+-3.141593") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:25: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("+-3") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:28: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("-3.141593") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:30: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("-3.141593") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:32: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("-3.1") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:34: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("+-3.141593") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:36: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("+-3.1") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:39: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("true") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:41: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("yes") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:43: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("true") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:46: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("mock") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:48: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("Mock") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:50: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("<NSObject: 0x13377fc60>") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:53: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("3") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:55: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("3") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:57: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("+3") is not equal to ("<redacted>")
/Users/Shared/OpenSource/Logging/Tests/LoggingTests/Test+Private.swift:59: error: -[LoggingTests.PrivateTests testPrivate] : XCTAssertEqual failed: ("+3") is not equal to ("<redacted>")
Test Case '-[LoggingTests.PrivateTests testPrivate]' failed (0.239 seconds).
Test Suite 'PrivateTests' failed at 2021-09-22 15:58:43.972.
	 Executed 1 test, with 20 failures (0 unexpected) in 0.239 (0.239) seconds
Test Suite 'PublicTests' started at 2021-09-22 15:58:43.972
Test Case '-[LoggingTests.PublicTests testPublic]' started.
Test Case '-[LoggingTests.PublicTests testPublic]' passed (0.000 seconds).
Test Suite 'PublicTests' passed at 2021-09-22 15:58:43.972.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'LoggingPackageTests.xctest' failed at 2021-09-22 15:58:43.973.
	 Executed 5 tests, with 20 failures (0 unexpected) in 0.241 (0.241) seconds
Test Suite 'All tests' failed at 2021-09-22 15:58:43.973.
	 Executed 5 tests, with 20 failures (0 unexpected) in 0.241 (0.242) seconds
```

### PR DESCRIPTION
**Pull request by GeekAndDad**
Issue #2 

## Describe your changes

From the commit:  Alternate method of fixing this issue which allows tests to run in both Release or Debug configurations via a new DEBUG build only configuration variable in `LogPrivacy` which may be set in tests.

### CODE REVIEW

**Comment by GeekAndDadDad** [comment]
This branch doesn't build since the last commit on shaps80/Logging was merged into it.
Get an error saying: "Module 'Logging' was not compiled for testing"

**Review by shaps80 — APPROVED** [review]
Agreed, this is great. I hadn't considered a static property that's only available in DEBUG, I love this approach. Also as you mentioned, it resolves the unsafeFlags issue so I'm gonna merge and release this. Thanks @GeekAndDadDad

**Comment by haikusw** [comment]
You're welcome.

I was tempted to remove the .xcscheme file entirely but didn't know if there was anything else you'd intentionally set it in for other reasons.  Might as well remove it if there isn't any other reason for it.

**Comment by GeekAndDad** [comment]
You're welcome.

I was tempted to remove the .xcscheme file entirely but didn't know if there was anything else you'd intentionally set it in for other reasons. Might as well remove it if there isn't any other reason for it.

**Pull request merged**
